package net.ornithemc.osl.datagen.api.provider;

import net.ornithemc.osl.datagen.api.PackCache;

import java.io.IOException;

/**
 * A provider for pack resources generated by a ModDataGenerator.
 */
public interface ModDataProvider {
    /**
     * Gets the name of this provider.
     * @return the name of this provider
     */
    String getProviderName();

    /**
     * Provides pack resources to the given cache.
     * @param cache the cache to provide pack resources to
     * @throws IOException if an I/O error occurs
     */
    void provide(PackCache cache) throws IOException;
}
