package net.ornithemc.osl.datagen.api.provider;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import net.fabricmc.loader.api.ModContainer;
import net.minecraft.block.Block;
import net.minecraft.entity.EntityType;
import net.minecraft.item.Item;
import net.minecraft.resource.Identifier;
import net.minecraft.world.biome.Biome;
import net.ornithemc.osl.core.api.util.NamespacedIdentifier;
import net.ornithemc.osl.datagen.api.PackGenerator;
import net.ornithemc.osl.resource.loader.api.resource.ResourcePath;
import net.ornithemc.osl.resource.loader.api.resource.ResourceType;

import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.function.BiConsumer;

/**
 * A provider for language files generated by a ModDataGenerator.
 */
public abstract class ModLanguageProvider extends GsonPackProvider {
    private final String languageCode;

    /**
     * Constructs a {@code ModLanguageProvider} with the specified generator, mod, and language code.
     *
     * @param generator the pack generator responsible for creating and registering resources
     * @param mod the mod container providing metadata and context for the mod
     * @param languageCode the language code to use for the language file
     */
    protected ModLanguageProvider(PackGenerator generator, ModContainer mod, String languageCode) {
        super(generator, mod);
        this.languageCode = languageCode;
    }

    /**
     * Constructs a {@code ModLanguageProvider} with the specified generator and mod,
     * using "en_us" as the default language code.
     *
     * @param generator the pack generator responsible for creating and registering resources
     * @param mod the mod container providing metadata and context for the mod
     */
    protected ModLanguageProvider(PackGenerator generator, ModContainer mod) {
        this(generator, mod, "en_us");
    }

    @Override
    protected final void generate(BiConsumer<NamespacedIdentifier, JsonElement> consumer) {
        Map<String, String> translations = new HashMap<>();

        generateTranslations(translations::put);

        JsonObject jsonObject = new JsonObject();
        translations.forEach(jsonObject::addProperty);

        consumer.accept(new Identifier(mod.getMetadata().getId(), this.languageCode), jsonObject);
    }

    /**
     * Generates translations for the language file.
     *
     * @param builder the translation builder to use for adding translations
     */
    protected abstract void generateTranslations(TranslationBuilder builder);

    @Override
    protected Path getPath(NamespacedIdentifier id) {
        return this.generator.getOutputPath().resolve(ResourcePath.nameOf(ResourceType.CLIENT_ASSETS, id.prefixed("lang").suffixed(".json")));
    }

    @Override
    public String getProviderName() {
        return String.format("Language (%s)", this.languageCode);
    }

    /**
     * A builder for language translations.
     */
    public interface TranslationBuilder {
        /**
         * Adds a translation for the specified key and value.
         *
         * @param key the translation key
         * @param value the translation value
         */
        void add(String key, String value);

        /**
         * Adds a translation for the specified block and value.
         *
         * @param block the block to add a translation for
         * @param value the translation value
         */
        default void add(Block block, String value) {
            this.add(block.getTranslationKey(), value);
        }

        /**
         * Adds a translation for the specified item and value.
         *
         * @param item the item to add a translation for
         * @param value the translation value
         */
        default void add(Item item, String value) {
            this.add(item.getTranslationKey(), value);
        }

        /**
         * Adds a translation for the specified entity type and value.
         *
         * @param entityType the entity type to add a translation for
         * @param value the translation value
         */
        default void add(EntityType<?> entityType, String value) {
            this.add(entityType.getTranslationKey(), value);
        }

        /**
         * Adds a translation for the specified biome and value.
         *
         * @param biome the biome to add a translation for
         * @param value the translation value
         */
        default void add(Biome biome, String value) {
            this.add(biome.getTranslationKey(), value);
        }
    }
}
