package net.ornithemc.osl.datagen.api;

import com.google.common.hash.HashFunction;
import com.google.common.hash.Hashing;

import java.io.IOException;
import java.nio.file.Path;

/**
 * A cache for pack resources generated by a ModDataGenerator.
 */
public interface PackCache {
    HashFunction SHA1 = Hashing.sha1();

    /**
     * Checks if the data for the given path has changed and writes it to the cache if it has.
     * @param path the path to check
     * @param data the data to write
     * @throws IOException if an I/O error occurs
     */
    void checkAndWrite(Path path, byte[] data) throws IOException;

    /**
     * Checks if the data for the given path has changed and writes it to the cache if it has.
     * @param path the path to check
     * @param data the data to write
     * @throws IOException if an I/O error occurs
     */
    void checkAndWrite(Path path, String data) throws IOException;
}
